### ISSUE TITLE
Using file type in your form raises error

### ISSUE THREAD

**Issue by basvdijk** [formly-js/angular-formly#384]
I have copied the form code from http://angular-formly.com/ main page into http://jsbin.com/mukisusitu/edit?html,css,js,output which throws an error telling there is no type by the name of "file". 

```
Error: Formly Error: There is no type by the name of "file": {"key":"file","type":"file","templateOptions":{"label":"File input","description":"Example block-level help text here","url":"https://example.com/upload"},"$$hashKey":"object:5","data":{},"validation":{"messages":{}},"id":"vm.form_file_file_0","name":"vm.form_file_file_0"}. 
    at getFormlyError (http://rawgit.com/formly-js/angular-formly/master/dist/formly.js:490:13)
    at formlyConfig.getType (http://rawgit.com/formly-js/angular-formly/master/dist/formly.js:712:14)
    at getFieldTemplate (http://rawgit.com/formly-js/angular-formly/master/dist/formly.js:1547:30)
    at fieldLink (http://rawgit.com/formly-js/angular-formly/master/dist/formly.js:1373:6)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:8636:44
    at invokeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:8642:9)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:8142:11)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:7534:13)
    at publicLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:7409:30)
    at name.$get.boundTranscludeFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:7553:16) <div formly-field="" ng-repeat="field in fields " ng-if="!field.hide" class="formly-field ng-scope ng-isolate-scope formly-field-file" options="field" model="field.model || model" fields="fields" form="theFormlyForm" form-id="formly_1" form-state="options.formState" form-options="options" index="$index">
```

the field is defined with:

```
    {
      key: 'file',
      type: 'file',
      templateOptions: {
        label: 'File input',
        description: 'Example block-level help text here',
        url: 'https://example.com/upload'
      }
    }
```

Any thoughts?

**Comment by kentcdodds** [comment]
Yeah, I should just update that page because you're not the first to be confused by it. In the code that you copy/pasted, you'll see this comment:

```javascript
// note, these field types will need to be
// pre-defined. See the pre-built and custom templates
// http://docs.angular-formly.com/v6.4.0/docs/custom-templates
```

I have an issue on the website repo to improve the homepage... Maybe I should do that soon... https://github.com/formly-js/angular-formly-website/issues/20
