### ISSUE TITLE
Error on http://angular-formly.com/#/ page

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/angular-formly#636]
SyntaxError: Unexpected token }
    at Object.parse (native)
    at Q (http://angular-formly.com/bundle.js:24:5415)
    at vt (http://angular-formly.com/bundle.js:25:10634)
    at http://angular-formly.com/bundle.js:25:11103
    at a (http://angular-formly.com/bundle.js:24:829)
    at wt (http://angular-formly.com/bundle.js:25:11085)
    at o (http://angular-formly.com/bundle.js:25:11812)
    at l (http://angular-formly.com/bundle.js:25:30362)
    at http://angular-formly.com/bundle.js:25:30534
    at m.$eval (http://angular-formly.com/bundle.js:26:6020)

**Comment by kentcdodds** [comment]
Thanks for letting me know! This should be fixed in a few minutes. Sorry about that!

**Comment by kentcdodds** [comment]
Please re-open this if it's not fixed in 30 minutes.
